# Generated by Django 5.2.9 on 2026-01-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0002_user_remove_course_students_delete_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="last_name",
            new_name="u_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="agg",
        ),
        migrations.RemoveField(
            model_name="user",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="enrollment_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_id",
        ),
    ]
