# Generated by Django 5.2.11 on 2026-02-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0003_rename_first_name_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="v_status",
            field=models.IntegerField(default=0),
        ),
    ]
